### ISSUE TITLE
company statistics  in all buffer

### ISSUE THREAD

**Issue by rosrad** [company-mode/company-statistics#1]
Here I have some troubles when i using the company-statistics,

I can only using the company-statistics in the text-mode, but the other program mode or org-mode.

can u give some advice about this , thank you

**Comment by ilohmar** [comment]
Hi rosrad,

there is nothing buffer/mode-specific in company-statistics, so if you've enabled it per the instructions, you're good to go.  What makes you think that it is not working in those non-text-modes?

Note that you still have to make sure that company-mode itself is enabled, company-statistics is just a kind of "add-on" to it.

If you continue to have problems, please give some more info:  What exactly do you do, what do you expect to happen, and what does happen instead?

**Comment by ilohmar** [comment]
Closing this for lack of updates.  Feel free to reopen.
