### ISSUE TITLE
Update statistics even if completion not accepted

### ISSUE THREAD

**Issue by raxod502** [company-mode/company-statistics#11]
I've noticed that `company-statistics`'s statistics are only updated when I explicitly accept a suggestion from `company-mode`, and not when I implicitly accept the suggestion by typing in the entire match.

For example, let's say I type in `agg` and get lots of matches from `company` because I have `aggressive-indent-mode` installed. Now, what I really want is `aggressive-indent-mode`, so I type that in and press `SPC`. But then the next time I type in `agg`, `aggressive-indent-mode` is not at the top of the list, since I did not explicitly accept the suggestion from `company` for `aggressive-indent-mode` and therefore `company-statistics` did not update.

My workaround is to force myself to explicitly accept suggestions from `company-mode` when I think that I might want them to be at the top of the list next time. But I can't think of any downsides to also updating the statistics database if the user happens to type in something that matches one of the `company-mode` suggestions and then dismisses the `company-mode` menu—at the very least the data would be much more rich, and `company-statistics` would appear to be smarter.

**Comment by ilohmar** [comment]
Hi, sorry for my very late reply.  I understand the issue, but I do not think there is an easy solution, at least not in `company-statistics`.  If `company-mode` would register such explicit typing as a completion, the statistics part would just work.  But from `company-mode`'s perspective, that does not make sense at all --- there *is* no completion in your scenario.

It sounds like what you want is rather general typing statistics influencing company's completion sorting.  I vaguely recall 'predictive-mode' (or similar) doing something like that, maybe that is what you're looking for?

**Comment by raxod502** [comment]
I don't know what the objectively best way to do completion sorting is. Maybe using general typing statistics would be better. I would obviously want the sorting to be per-mode, like `company-statistics` already does, though.

I will open an issue upstream in `company-mode` to add an option for this (or I will find that such a feature already exists, and close this one).

**Comment by raxod502** [comment]
I found no existing option for this. See https://github.com/company-mode/company-mode/issues/719.

**Comment by dgutov** [comment]
If you're still considering this feature request, you can use `company-completion-cancelled-hook` for it.

**Comment by raxod502** [comment]
I now use [`prescient.el`](https://github.com/raxod502/prescient.el) instead of `company-statistics`, so I'll close this issue and think about how I can implement the feature in `prescient.el` using that hook—thanks @dgutov (see https://github.com/raxod502/prescient.el/issues/23).

Feel free to reopen if you're interested in the feature for `company-statistics`.

**Comment by raxod502** [comment]
@dgutov I was looking at this, and it seems like I can't use `company-completion-cancelled-hook` as is, because it doesn't tell me what candidate was implicitly accepted. Is there a good approach for figuring out what the candidate was, or do I have to resort to a hack?

**Comment by dgutov** [comment]
Sorry, no. There is no easy way to do it, aside from something like saving the value of `(nth company-selection company-candidates)` in a post-command-hook function, and then acting upon it in `company-completion-cancelled-hook`.

**Comment by raxod502** [comment]
Could be a useful feature to add, but I see the complexity. Thanks for your response!
