### ISSUE TITLE
Select instead of sort.

### ISSUE THREAD

**Issue by jcs090218** [company-mode/company-statistics#13]
Do you think you can implement this feature? Just select the top most possible candidate instead of sort the completion? I think this is base on the personal habit and some editor do have this kind of feature. :D 

Instead of changing this list.
```
+-------+
| var2  |    <-- Candidate sorted!
+-------+
| var1  |
+-------+
```

Just make the current selection to that candidate!
```
+-------+
| var1  |
+-------+
| var2  |    <-- Highlight/Select this one!
+-------+
```

**Comment by ilohmar** [comment]
Hi there,

I don't think this can/should be implemented in `company-statistics`.  You could probably write a command to just use the first candidate, or hook into `company-completion-started-hook` (to select even if the completion was auto-started)

But this add-on should really not do anything like that: it's just an orthogonal feature, independent of sorting candidates.
