### ISSUE TITLE
Disables the completion popup list

### ISSUE THREAD

**Issue by swarnendubiswas** [company-mode/company-statistics#4]
Enabling this minor mode seems to disable the completion popup list, disabling the minor mode reenables the popup.  

I am not sure whether this is by design or an issue. Keeping the popup dialog unaffected seems to be the preferred choice.

**Comment by ilohmar** [comment]
I am not sure what you mean by the "completion popup list".  I understand you mean the overlay popup below/above point displaying the various completion choices?  If so, I cannot reproduce that issue at all.  Could you please describe exactly what you do, starting from "emacs -Q"?

**Comment by dgutov** [comment]
I cannot reproduce it either.

**Comment by swarnendubiswas** [comment]
Yes I meant the overlay popup. This is my company configuration from init.el (and I have other packages). 

(autoload 'company-mode "company" nil t)
(setq company-dabbrev-downcase nil 
      company-show-numbers t
      company-minimum-prefix-length 2)
(setq company-tooltip-flip-when-above t) 
(global-company-mode 1)
(company-auctex-init)
;;(company-statistics-mode 1)

Enabling statistics seems to disable the overlay. I sort of figured that out by commenting out different lines (the naive way).

@ilohmar: I did not understand your suggestion with "emacs -Q", doesn't it mean that no init files will be processed? It would help if you could explain the steps you are suggesting.

**Comment by ilohmar** [comment]
Exactly, since it is an issue specific to your setup, starting with none is always a good idea.  But it might be more efficient to do `M-x toggle-debug-on-error`; and then try to complete with the minor mode enabled.  If indeed company-statistics-mode makes a difference, it should produce some backtrace then, please post that.

Also important: Do you install from ELPA?  Do you use both latest versions?  And what is your emacs version?

**Comment by swarnendubiswas** [comment]
My GNU Emacs version is 24.4.1 (on RHEL 6.6), which I have compiled myself. 

Company version is 20150204.836, company-statistics is  0.1. 

I have both elpa and melpa repos enabled, I think the packages installed are from elpa. Is there a way to find that out?

I am not aware of how can I start/enable company mode after starting emacs with -Q flag. M-x does not show company-mode as options, do I need to add to load-paths or anything?

Instead this is what I did: I used an empty init.el file, opened a .tex, enabled company-mode and can see and use the overlay. Then I enabled company-statistics-mode and overlay is gone. The minibuffer has this error "Wrong type argument: hash-table-p, nil".

**Comment by ilohmar** [comment]
Do you have a file `company-statistics-cache.el` in your user directory (where you have your `init.el` file)?  What is its content?  (Feel free to remove any sensitive information.)

The error you describe happens when you have erroneous content in that file.  It should not happen if you start without such a file, ie, deleting it and repeating your steps should not produce the error.

**Comment by swarnendubiswas** [comment]
Yes, the file exists under ~/.emacs.d.  This is the content:

(setq company-statistics--scores nil company-statistics--log nil company-statistics--index nil)

You are right, deleting the file helps, overlays are now there even with statistics enabled. I didn't tamper with it though.

**Comment by ilohmar** [comment]
> I didn't tamper with it though.

Understood, thanks for your help.  It seems https://github.com/company-mode/company-statistics/issues/3 was the same thing, basically. I am going to make the save/load cycle more robust tonight.

**Comment by ilohmar** [comment]
Aaah... got the issue, I think.  My fault, it occurs in an install situation that I probably never tested (package is loaded but never enabled before quitting emacs)...

Fix tonight, off to work now...

**Comment by swarnendubiswas** [comment]
Thanks for helping, I will close this issue then.

**Comment by ilohmar** [comment]
Hi, the fix is in (though it will no longer affect you).  As I am just getting started with ELPA development, it might take a little while before the official package gets it.

**Comment by dgutov** [comment]
@ilohmar Should I do the push now?

**Comment by ilohmar** [comment]
Just got emacs group membership 1h ago :)  Thanks for asking, I am getting my head around a few things to try and handle it myself.  One thing I would like to know: How do you handle the synchronization from the github repo to the elpa repo --- I hope there is a more clever way than just recreating commits?  Sorry for any blatant ignorance on my part...

**Comment by dgutov** [comment]
I do it with `git subtree merge`. `git subtree` is a contrib utility.

See https://lists.gnu.org/archive/html/emacs-devel/2013-08/msg00387.html, or maybe search emacs-devel for the recent messages on this subject (there have been some).

**Comment by ilohmar** [comment]
Thanks for the pointers!  I'll read up on this and will get it out this weekend.
