### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by raxod502** [company-mode/company-statistics#9]
Are there any objections to putting `company-statistics` on MELPA?

**Comment by dgutov** [comment]
Not exactly an objection, but why?

It doesn't update very often, and you'll need the GNU ELPA repository anyway, for other basic packages.

**Comment by raxod502** [comment]
Actually, AFAIK this is the only package I use that I need GNU ELPA for. I ran into trouble when I tried to switch over my entire Emacs configuration to load packages with [quelpa](https://github.com/quelpa/quelpa) (actually [quelpa-use-package](https://github.com/quelpa/quelpa-use-package)). Everything worked seamlessly, since quelpa draws recipes from MELPA, except for `company-statistics`, where I had to write my own recipe.

Not exactly hard, but why not make it more convenient for everyone? :)

**Comment by dgutov** [comment]
Either way, there's nothing to be changed here. File an issue at MELPA's repo, maybe?

**Comment by raxod502** [comment]
Will do. I filed this issue first because MELPA's contributing guidelines suggest:

> If you are not the original author or maintainer of the package you are submitting, please consider notifying the author prior to submitting and make reasonable effort to include them in the pull request process.

**Comment by raxod502** [comment]
From the pull request on MELPA:

> There are following byte-compile warnings.
> 
>     company-statistics.el:116:1:Warning: Unused lexical argument ‘option’
>     company-statistics.el:165:1:Warning: Unused lexical argument ‘cand’
>     company-statistics.el:215:1:Warning: Unused lexical argument ‘manual’
>     company-statistics.el:225:1:Warning: Unused lexical argument ‘cand’
> 
> If those variables are surely unused, please prepend _ to them like _option for suppressing byte-compile warnings.

**Comment by syohex** [comment]
company-statistics is registered at MELPA now. This issue can be closed.
